name: Docker

on:
  push:
    branches: [main]
    tags: ["contracts-v*"]

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/stellarrail/stellarrail-contracts
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/stellarrail/stellarrail-contracts
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
